### ISSUE TITLE
Action builds in development environment

### ISSUE THREAD

**Issue by ptmerz** [EdricChan03/action-build-deploy-ghpages#21]
Hi,
thank you for offering this very useful action!

The action builds the Jekyll site in the (default) `development` environment. More details about environments here: https://jekyllrb.com/docs/configuration/environments/

The type of environment the site is built on does often matter. For example, both Minima and Minimal Mistakes only turn on comments in the posts if they are built in the `production` environment. Minimal Mistakes also turns off analytics for `development` environments.

This is not a bug, rather something that tripped me up and cost me a bit of time to figure out, so I thought I'd bring it to your attention!

A simple solution is to add an environment variable, like
```
steps:
  - uses: actions/checkout@v2
  - uses: EdricChan03/action-build-deploy-ghpages@v2.5.0
    env:
      JEKYLL_ENV: 'production'
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
```

I think this example could be added as part of the documentation, together with a few examples of why this might matter. (You could also think about making the `production` environment the default, which might be closer to what people need when deploying their site, but that might break some existing workflows.)
